# Generated by Django 5.1.3 on 2024-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_experience_aboutme_avatar_aboutme_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
